/******************************************************************************
 *
 * Module: Ultrasonic Sensor (HC-SR04)
 *
 * File Name: Ultrasonic.h
 *
 * Description: Header file for the Ultrasonic Sensor driver
 *
 * Author: Mohamed Baleegh
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                         Configurations   and    Definitions                                    *
 *******************************************************************************/

/*  Trigger pin connection */
#define ULTRASONIC_TRIGGER_PORT_ID    PORTD_ID
#define ULTRASONIC_TRIGGER_PIN_ID     PIN7_ID



/* Speed of sound  */
#define ULTRASONIC_SOUND_SPEED_CM_US  0.0343  /* 343 m/s = 0.0343 cm/us */

/* Timer tick time in us for F_CPU=16MHz and Prescaler=8 */
#define ULTRASONIC_TIMER_TICK_US      0.5



/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 *  Description :1- Initialize the ICU driver as required.
                 2- Setup the ICU call back function.
                 3- Setup the direction for the trigger pin as output pin through the GPIO driver.
     Inputs      : None
     Return      : None
 * */
void Ultrasonic_init(void);

/*
• Description : Send the Trigger pulse to the ultrasonic.
• Inputs      : None
• Return      : None
 */

void Ultrasonic_Trigger(void);

/*
• Description : 1- Send the trigger pulse by using Ultrasonic_Trigger function.
                2- Start the measurements by the ICU from this moment.
• Inputs      : None
• Return      : The measured distance in cm
 */

uint16 Ultrasonic_readDistance(void);

/*
 • Description : 1-This is the call back function called by the ICU driver.
               : 2-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 • Inputs      : None
 • Return      : None
 */

void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
